/*
# MIT License
#
# Copyright (c) 2025 Reed A. Cartwright <racartwright@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

Example Usage: ./ironseed-bin 1 | RNG_test stdin32 -tlmax 16GB
./ironseed-bin $(od -vAn -N32 -t u4 < /dev/urandom) | RNG_test stdin32 -tlmax 16GB
*/

#include <assert.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>

typedef struct ironseed_hash {
  uint64_t coef;
  uint64_t hashes[8];
} ironseed_hash_t;

typedef struct ironseed {
  uint32_t seed[8];
} ironseed_t;

// Four random primes generated by Mathematica
// NextPrime[RandomInteger[{0, 2^64-1}]]
// IntegerString[%, 16]
static const uint64_t PRIME_A = 0xc9f736a1a00d1f5f;
static const uint64_t PRIME_B = 0x88226cde0de826bf;
static const uint64_t PRIME_C = 0x278abb429678dd43;
static const uint64_t PRIME_D = 0x7aa8bb10afef725b;

// Multilinear hash (https://arxiv.org/pdf/1202.4961.pdf)
// Hash is based on a sequence of 64-bit numbers generated by Weyl sequence
// Multilinear hash is (m_0 + sum(m_i*u_i) mod 2^64) / 2^32
// m = buffer of 64-bit unsigned random values
// u = 32-bit input values that are being hashed

static inline uint64_t init_hash4i_coef(void) { return PRIME_A; }

static inline uint64_t hash4i_coef(uint64_t *m) { return *m += PRIME_B; }

static inline uint64_t init_hash4o_coef(void) { return PRIME_C; }

static inline uint64_t hash4o_coef(uint64_t *m) { return *m += PRIME_D; }

static inline uint32_t finalmix(uint64_t u) {
  // Final mixing adapted from splitmix64
  u = (u ^ (u >> 30)) * 0xbf58476d1ce4e5b9;
  u = (u ^ (u >> 27)) * 0x94d049bb133111eb;
  return u >> 32;
}

// Initialize an ironseed_hash object. Stores the intermediate values of
// 8 multilinear hashes as additional values are added to the hash.
static void init_ironseed_hash(ironseed_hash_t *p) {
  assert(p != NULL);
  p->coef = init_hash4i_coef();
  for(int i = 0; i < 8; ++i) {
    p->hashes[i] = hash4i_coef(&p->coef);
  }
}

// Update the intermediate state of each sub-hash.
static void update_ironseed_hash(ironseed_hash_t *p, uint32_t value) {
  assert(p != NULL);
  for(int i = 0; i < 8; ++i) {
    p->hashes[i] += hash4i_coef(&p->coef) * value;
  }
}

static void create_ironseed(const ironseed_hash_t *p, ironseed_t *v) {
  assert(p != NULL);
  assert(v != NULL);

  // If the last valued hashed was 0, then it did not affect the hash
  // value. It did affect the coefficients. Append one extra value to
  // the end before we generate the result of each hash.
  uint64_t k = p->coef;
  for(int i = 0; i < 8; ++i) {
    uint64_t u = p->hashes[i] + hash4i_coef(&k);
    v->seed[i] = finalmix(u);
  }
}

static uint32_t create_seedseq(const ironseed_t *p, uint64_t *pm) {
  assert(p != NULL);
  assert(pm != NULL);

  uint64_t u = hash4o_coef(pm);
  
  for(int j = 0; j < 8; ++j) {
    u += hash4o_coef(pm) * p->seed[j];
  }

  return finalmix(u);
}

int main(int argc, char const *argv[]) {
	ironseed_hash_t h;
	ironseed_t fe;
	init_ironseed_hash(&h);

	for(int i = 1; i < argc; ++i) {
		uint32_t v = (uint32_t)strtoul(argv[i], NULL, 0);
		update_ironseed_hash(&h, v);
	}
	create_ironseed(&h, &fe);

	uint64_t k = init_hash4o_coef();

  for(;;) {
    uint32_t v = create_seedseq(&fe, &k);
    fwrite((void*) &v, sizeof(v), 1, stdout);
  }

	return EXIT_SUCCESS;
}
