on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:
    inputs:
      release:
        description: 'DragonFlyBSD release'
        required: true
        type: choice
        options:
        - '6.4.0'
        default: '6.4.0'

name: dragonflybsd.yaml

jobs:
  dragonflybsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-hub/actions/setup-r-dragonflybsd@v1
        with:
          release: ${{ github.event.inputs.release || '6.4.0' }}
      - uses: r-hub/actions/platform-info@v1

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: none
          install-pandoc: false
          install-quarto: false
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
          upload-snapshots: true
          upload-results: true
          artifact-name: ${{ format('{0}-{1}-r{2}-{3}-results', 'dragonflybsd', runner.arch, matrix.config.r, matrix.config.id || strategy.job-index ) }}

